FROM node:19.0.0-alpine

WORKDIR /usr/src/app

# Déclaration des arguments de build
ARG NEXT_PUBLIC_USERNAME
ARG NEXT_PUBLIC_EMAIL
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG EMAIL_USER
ARG EMAIL_PASSWORD

# Conversion des ARG en ENV pour les rendre disponibles pendant le build
ENV NEXT_PUBLIC_USERNAME=$NEXT_PUBLIC_USERNAME
ENV NEXT_PUBLIC_EMAIL=$NEXT_PUBLIC_EMAIL
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ENV EMAIL_USER=$EMAIL_USER
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000
CMD [ "npm", "start" ]